config/routes.rb
Rails.application.routes.draw do

  if Rails.env.development?
    root 'main#amalgam'
  else
    root 'main#home'
  end

  get 'home' => "main#home"

  resources :games do   
    resources :brackets do
      resources :maps do
        resources :gametypes
      end
    end
  end
  resources :brackets, only: :index
  
  resources :tournaments

  resources :examples

  devise_for :users
  devise_scope :user do
    get '/signout', to: 'devise/sessions#destroy', as: :signout
  end

  resources :users

  get 'admin/main' => 'admin_panels#main'
  get 'control' => 'admin_panels#control_panel'

  get 'new-form' => 'examples#new_form'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

    def initialize(user)
      user ||= User.new # guest user (not logged in)
        if user.admin?
          can :manage, :all

          can :delete, User do |user|
            !user.admin?
          end
          
        else
          can :read, :all
          # can :manage, Bracket
          # can :manage, :all. if: { }
        end
    end

    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities

end

app/models/bracket.rb
class Bracket < ActiveRecord::Base
	belongs_to :game
	
	has_many :maps
	has_many :gametypes
end

app/models/example.rb
class Example < ActiveRecord::Base
end

app/models/game.rb
class Game < ActiveRecord::Base
	has_attached_file :image_file, styles: {large: "750x500>", medium: "450x450>", small: "300x250>", tiny: "100x100>" }, default_url: "/images/:style/missing.png"
	validates_attachment_content_type :image_file, content_type: /\Aimage\/.*\z/

	validates_uniqueness_of :title

	has_many :brackets
	has_many :gametypes
	has_many :maps

	scope :fps, -> { where(category: 'fps') }
	scope :moba, -> { where(category: 'moba') }
	scope :more, -> { where(category: 'more') }
	scope :legacy, -> { where(category: 'legacy') }

end

app/models/gametype.rb
class Gametype < ActiveRecord::Base
  belongs_to :game
  belongs_to :map
  belongs_to :bracket
end

app/models/map.rb
class Map < ActiveRecord::Base
  belongs_to :game
  belongs_to :bracket
  has_many :gametypes
end

app/models/tournament.rb
class Tournament < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, except: [:index, :new, :create]
  load_and_authorize_resource

  def index
    @games = Game.all 
  end

  def new
    @game = Game.new
  end

  def create
    @game = Game.new(game_params)
    if @game.save
      redirect_to games_path
    else
      render :new 
    end
  end

  def edit

  end

  def update
     @game.update(game_params)
     redirect_to games_path
  end

  def show
  end

  def destroy
    @game.destroy
    flash[:success] = "Game Destroyed"
    redirect_to games_path
  end

  private

  def set_game 
    @game = Game.find(params[:id])
  end

  def game_params
    params.require(:game).permit(:image, :title, :category, :active, :short_title, :image_file)
  end

end

app/controllers/main_controller.rb
class MainController < ApplicationController
	
	# layout "_hero"

  def home
  end

  def amalgam
  end

  def layout
  end

end

app/controllers/maps_controller.rb
class MapsController < ApplicationController

  before_action :set_game, :set_bracket
  before_action :set_map, except: [:new, :create, :index]

  def index
    @maps = @bracket.maps
  end

  def new
    @map = @bracket.maps.new
  end

  def create
    @map = @bracket.maps.new(map_params)
    if @map.save
      flash[:success] = "Map succesfully saved."
      redirect_to game_bracket_maps_path(@game, @bracket)
    end
  end

  def edit
  end

  def update
  end

  def show

  end

  def destroy
  end

  private 

  def set_map
    if params[:map_id].present?
      @map = Map.find(params[:map_id])
    else
      @map = Map.find(params[:id])
    end
  end

  def map_params 
    params.require(:map).permit(:name)
  end

  def set_game
    if params[:game_id].present?
      @game = Game.find(params[:game_id])
    end    
  end

  def set_bracket
    if params[:bracket_id].present?
      @bracket = Bracket.find(params[:bracket_id])
    end
  end  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def new
    @user = User.new 
  end

  def create
    @user = User.create(user_params)
    if @user.save 
      redirect_to users_path
    else
      render :new
    end
  end

  def edit
  end

  def update
  end

  def show
  end

  def destroy
  end

  private

  def set_params
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :admin)
  end

end

app/helpers/admin_panels_helper.rb
module AdminPanelsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brackets_helper.rb
module BracketsHelper
end

app/helpers/examples_helper.rb
module ExamplesHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/gametypes_helper.rb
module GametypesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/tournaments_helper.rb
module TournamentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/main/amalgam.html.erb
<h1>Main#amalgam</h1>
<p>Find me in app/views/main/amalgam.html.erb</p>


<%= link_to "Home", home_path %> <br>

<% if user_signed_in? %>
	<%= link_to "Log out", signout_path %>
<% else %>
	<%= link_to "Sign up", new_user_registration_path %>
	<%= link_to "Log in", new_user_session_path %>
<% end %>

<% if user_signed_in? %>
	<p><%= current_user.email %></p>
<% end %>

<% if user_signed_in? %>
	<%= link_to "Edit Profile", edit_user_registration_path %>
<% end %>

<p><%= link_to "Users Index", users_path %></p>
<p><%= link_to "Games Index", games_path %></p>
<p><%= link_to "Brackets Index", brackets_path %></p>

FPS Games: 
<% Game.fps.each do |x| %> 
	<div class="fps-item"></div>
	<p><%= x.title %></p>
	<p><%= image_tag x.image_file.url(:small) %></p>
<% end %>

<% Game.moba.each do |x| %>
	<div class="moba-item"></div>
	<p><%= x.title %></p>
	<p><%= image_tag x.image_file.url(:small) %></p>
<% end %>

<% Game.more.each do |x| %>
	<div class="more-item"></div>
	<p><%= x.title %></p>
	<p><%= image_tag x.image_file.url(:small) %></p>
<% end %>

<% Game.legacy.each do |x| %>
	<div class="legacy-item"></div>
	<p><%= x.title %></p>
	<p><%= image_tag x.image_file.url(:small) %></p>
<% end %>

<!-- <div class="games-group" style="background-color: black;">
	<div class="box"></div>
		<% Game.fps.each do |x| %>
		<div class="col-3">
			<%= image_tag x.image_file.url(:large), height: "250", width: "250" %>
		</div>
		<% end %>
	</div>
</div> -->

app/views/main/home.html.erb
<!-- <h1>Main#home</h1>
<p>Find me in app/views/main/home.html.erb</p>
 -->

<div class="box games-set">
	<% Game.fps.each do |game| %> 
		<div class="col-3 full-view">
			<div class="game-box game-box-fps">
				<%= link_to image_tag(game.image_file.url(:original), :class => "game-img"), game %>
				<p class="game-info">
					<span class="tall-text">
						<% if game.title.length >= 25 %>
							<%= game.short_title %>
						<% else %>
							<%= game.title %>	
						<% end %> 
					</span>
				<span class="num-play">Players</span></p>
			</div>
		</div>
	<% end %>
</div>

<div class="box games-set">
	<% Game.moba.each do |game| %> 
		<div class="col-3 full-view">
			<div class="game-box game-box-moba">
				<%= link_to image_tag(game.image_file.url(:original), :class => "game-img"), game %>
					<p class="game-info">
					<span class="tall-text">
						<% if game.title.length >= 25 %>
							<%= game.short_title %>
						<% else %>
							<%= game.title %>	
						<% end %> 
					</span>
				<span class="num-play">Players</span></p>
			</div>
		</div>
	<% end %>
</div>

<div class="box games-set">
	<% Game.more.each do |game| %> 
		<div class="col-3 full-view">
			<div class="game-box game-box-more">
				<%= link_to image_tag(game.image_file.url(:original), :class => "game-img"), game %>
					<p class="game-info">
					<span class="tall-text">
						<% if game.title.length >= 25 %>
							<%= game.short_title %>
						<% else %>
							<%= game.title %>	
						<% end %> 
					</span>
				<span class="num-play">Players</span></p>
			</div>
		</div>
	<% end %>
</div>

<div class="box games-set">
	<% Game.legacy.each do |game| %> 
		<div class="col-3 full-view">
			<div class="game-box game-box-legacy">
				<%= link_to image_tag(game.image_file.url(:original), :class => "game-img"), game %>
					<p class="game-info">
					<span class="tall-text">
						<% if game.title.length >= 22 %>
							<%= game.short_title %>
						<% else %>
							<%= game.title %>	
						<% end %> 
					</span>
				<span class="num-play">Players</span></p>
			</div>
		</div>
	<% end %>
</div>