config/routes.rb
Rails.application.routes.draw do

  if Rails.env.development?
    root 'main#amalgam'
  else
    root 'main#home'
  end

  get 'home' => "main#home"

  resources :games do   
    resources :brackets do
      resources :maps do
        resources :gametypes
      end
    end
  end
  resources :brackets, only: :index
  
  resources :tournaments

  resources :examples

  devise_for :users
  devise_scope :user do
    get '/signout', to: 'devise/sessions#destroy', as: :signout
  end

  resources :users

  get 'admin/main' => 'admin_panels#main'
  get 'control' => 'admin_panels#control_panel'

  get 'new-form' => 'examples#new_form'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

    def initialize(user)
      user ||= User.new # guest user (not logged in)
        if user.admin?
          can :manage, :all

          can :delete, User do |user|
            !user.admin?
          end
          
        else
          can :read, :all
          # can :manage, Bracket
          # can :manage, :all. if: { }
        end
    end

    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities

end

app/models/bracket.rb
class Bracket < ActiveRecord::Base
	belongs_to :game
	
	has_many :maps
	has_many :gametypes
end

app/models/example.rb
class Example < ActiveRecord::Base
end

app/models/game.rb
class Game < ActiveRecord::Base
	has_attached_file :image_file, styles: {large: "750x500>", medium: "450x450>", small: "300x250>", tiny: "100x100>" }, default_url: "/images/:style/missing.png"
	validates_attachment_content_type :image_file, content_type: /\Aimage\/.*\z/

	validates_uniqueness_of :title

	has_many :brackets
	has_many :gametypes
	has_many :maps

	scope :fps, -> { where(category: 'fps') }
	scope :moba, -> { where(category: 'moba') }
	scope :more, -> { where(category: 'more') }
	scope :legacy, -> { where(category: 'legacy') }

end

app/models/gametype.rb
class Gametype < ActiveRecord::Base
  belongs_to :game
  belongs_to :map
  belongs_to :bracket
end

app/models/map.rb
class Map < ActiveRecord::Base
  belongs_to :game
  belongs_to :bracket
  has_many :gametypes
end

app/models/tournament.rb
class Tournament < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/brackets_controller.rb
class BracketsController < ApplicationController
  before_action :set_game
  
  def index
    if @game.present?
      @brackets = @game.brackets 
    else
      @brackets = Bracket.all   
    end    
  end

  def new
    @bracket = Bracket.new
  end

  def create
    @bracket = @game.brackets.new(bracket_params)
    if @bracket.save 
      redirect_to game_brackets_path(@game)
    else
      render :new 
    end
  end

  def edit
  end

  def update
  end

  def show
    @bracket = Bracket.find(params[:id])
  end

  def destroy
  end

  private 

  def set_params 
  end

  def set_game
    if params[:game_id].present?
      @game = Game.find(params[:game_id])
    end    
  end


  def bracket_params 
    params.require(:bracket).permit(:title, :rounds, :team_size)
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, except: [:index, :new, :create]
  load_and_authorize_resource

  def index
    @games = Game.all 
  end

  def new
    @game = Game.new
  end

  def create
    @game = Game.new(game_params)
    if @game.save
      redirect_to games_path
    else
      render :new 
    end
  end

  def edit

  end

  def update
     @game.update(game_params)
     redirect_to games_path
  end

  def show
  end

  def destroy
    @game.destroy
    flash[:success] = "Game Destroyed"
    redirect_to games_path
  end

  private

  def set_game 
    @game = Game.find(params[:id])
  end

  def game_params
    params.require(:game).permit(:image, :title, :category, :active, :short_title, :image_file)
  end

end

app/controllers/main_controller.rb
class MainController < ApplicationController
	
	# layout "_hero"

  def home
  end

  def amalgam
  end

  def layout
  end

end

app/controllers/maps_controller.rb
class MapsController < ApplicationController

  before_action :set_game, :set_bracket
  before_action :set_map, except: [:new, :create, :index]

  def index
    @maps = @bracket.maps
  end

  def new
    @map = @bracket.maps.new
  end

  def create
    @map = @bracket.maps.new(map_params)
    if @map.save
      flash[:success] = "Map succesfully saved."
      redirect_to game_bracket_maps_path(@game, @bracket)
    end
  end

  def edit
  end

  def update
  end

  def show

  end

  def destroy
  end

  private 

  def set_map
    if params[:map_id].present?
      @map = Map.find(params[:map_id])
    else
      @map = Map.find(params[:id])
    end
  end

  def map_params 
    params.require(:map).permit(:name)
  end

  def set_game
    if params[:game_id].present?
      @game = Game.find(params[:game_id])
    end    
  end

  def set_bracket
    if params[:bracket_id].present?
      @bracket = Bracket.find(params[:bracket_id])
    end
  end  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def new
    @user = User.new 
  end

  def create
    @user = User.create(user_params)
    if @user.save 
      redirect_to users_path
    else
      render :new
    end
  end

  def edit
  end

  def update
  end

  def show
  end

  def destroy
  end

  private

  def set_params
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :admin)
  end

end

app/helpers/admin_panels_helper.rb
module AdminPanelsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brackets_helper.rb
module BracketsHelper
end

app/helpers/examples_helper.rb
module ExamplesHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/gametypes_helper.rb
module GametypesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/tournaments_helper.rb
module TournamentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/brackets/_form.html.erb
<%= form_for([@game, @bracket]) do |f| %>
	<% if @bracket.errors.any? %>
		<p><%= pluralize(@game.errors.count, "error") %> errors kept form from submitting succesfully:</p>

		<ul>
			<% @bracket.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
		</ul>
	<% end %>
	<%= f.label :title %><br>
	<%= f.text_field :title %> 
<p></p>
<%= f.label :rounds %><br>
	<%= f.text_field :rounds %>
<p></p>
	<%= f.label :team_size %><br>
	<%= f.text_field :team_size %>
<p></p>
<!-- 	<%= f.label :game_id %> <br>
	<%= f.select :game_id, Game.all.collect { |g| [ g.short_title, g.id ] }, include_blank: true, :class => "select-list" %> -->
<p></p>
	<%= f.submit %>
<% end %>

app/views/brackets/create.html.erb
<h1>Brackets#create</h1>
<p>Find me in app/views/brackets/create.html.erb</p>

app/views/brackets/destroy.html.erb
<h1>Brackets#destroy</h1>
<p>Find me in app/views/brackets/destroy.html.erb</p>

app/views/brackets/edit.html.erb
<h1>Brackets#edit</h1>
<p>Find me in app/views/brackets/edit.html.erb</p>

app/views/brackets/index.html.erb
<% if @game.present? %>
  <%= link_to "New Bracket", new_game_bracket_path(@game) %>

<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Bracket Title</th>
      <th>Maps</th>
      <th>Rounds</th>
      <th>Team Size</th>
      <th>Links</th>
    </tr>
  </thead>

  <tbody>
    <% @brackets.each do |bracket| %>
      <tr>
        <td><%= bracket.title %></td>
        <td><% bracket.maps.each_with_index do |map, index| %>
        <table>
          <thead>
            <tr>
              <th></th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td> Map: <%= index + 1 %> <%=  map.name %> </td>

              <!-- <td><%#= link_to "Gametypes", game_bracket_map_gametypes_path(@game, bracket, map) %></td> -->
              <td>
                <% map.gametypes.each do |gametype| %>
                    <p><%= gametype.name %></p>
                <% end %>
              </td>
            </tr>
          </tbody>
        </table>
        <% end %>
        <td><%= bracket.rounds %></td>
        <td><%= bracket.team_size %></td>
        <td><%= link_to "Maps", game_bracket_maps_path(@game, bracket) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<% else %>

<div class="box">
  <div class="col-3"></div>
  <div class="col-6">
    <table>
      <thead>
        <tr>
          <th>Game Title</th>
          <th>Brackets</th>                  
        </tr>
      </thead>
      <tbody>  
       <% Game.all.each do |game| %>       
        <tr>
          <td> <%= game.title %> </td>
          <td> <%= link_to "New Bracket", new_game_bracket_path(game) %> </td>
          <td>
            <table>
            <thead>
            <tr>
              <th>1</th>
              <th>2</th>
              <th>3</th>
              <th>4</th>
            </tr>
            </thead>
            <tbody>
              <tr>
                <% game.brackets.each do |bracket| %>
                  <td><%= bracket.title %>|</td>
                  <td> <%= link_to "show", game_bracket_path(game, bracket) %>|</td>
                  <td><%= link_to "edit", edit_game_bracket_path(game, bracket) %>|</td>
                  <td> <%= link_to "destroy", game_bracket_path(game, bracket), method: :delete, data: {confirm: "Are you sure?"} %>|</td>
                <% end %>
              </tr>
              </tbody>
            </table>
          </td>
      <% end %>
      </tbody>
    </table>
  </div> 
</div>
<% end %>

app/views/brackets/new.html.erb
<h1>Brackets#new</h1>
<p>Find me in app/views/brackets/new.html.erb</p>

<div class="w3-row-padding">
<%= render 'form' %>
</div>

app/views/brackets/show.html.erb
Title: <%= @bracket.title %>
	<br/>
Maps: 
	<br/>
<% @bracket.maps.each_with_index do |map, index| %>
	Map: <%= index + 1 %> <%=  map.name %>
	<br/>
<% end %>

app/views/brackets/update.html.erb
<h1>Brackets#update</h1>
<p>Find me in app/views/brackets/update.html.erb</p>

app/views/maps/_form.html.erb
<%= form_for([@game, @bracket, @map]) do |f| %>
	<% if @map.errors.any? %>
		<p><%= pluralize(@game.errors.count, "error") %> errors kept form from submitting succesfully:</p>

		<ul>
			<% @map.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
		</ul>
	<% end %>
	<%= f.label :name %><br>
	<%= f.text_field :name %> 
<p></p>
	<%= f.submit %>
<% end %>

app/views/maps/create.html.erb
<h1>Maps#create</h1>
<p>Find me in app/views/maps/create.html.erb</p>

app/views/maps/destroy.html.erb
<h1>Maps#destroy</h1>
<p>Find me in app/views/maps/destroy.html.erb</p>

app/views/maps/edit.html.erb
<h1>Maps#edit</h1>
<p>Find me in app/views/maps/edit.html.erb</p>

app/views/maps/index.html.erb
<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Name:</th>
      <th>Game Title</th>
      <th>Bracket Title</th>
    </tr>
  </thead>

  <tbody>
    <% @maps.each do |map| %>
      <tr>
        <td><%= map.name %></td>
        <td><%= map.bracket.game.title %></td>
        <td><%= map.bracket.title %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "New Map", new_game_bracket_map_path(@game, @bracket) %>

app/views/maps/new.html.erb
<h1>Maps#new</h1>
<p>Find me in app/views/maps/new.html.erb</p>

<%= render "form" %>

app/views/maps/show.html.erb
Map: <%= @map.name %>
Game: <%= @map.bracket.game.title %>
Bracket: <%= @map.bracket.title %>

app/views/maps/update.html.erb
<h1>Maps#update</h1>
<p>Find me in app/views/maps/update.html.erb</p>

app/views/users/_form.html.erb
<%= form_for(@user) do |u| %>
	<%= u.label :first_name %>
	<%= u.text_field :first_name %>
	<p></p>
	<%= u.label :last_name %>
	<%= u.text_field :last_name %>
	<p></p>
	<%= u.label :admin %>
	<%= u.select :admin, [["True", true], ["False", false]] %>

	<%= u.submit %>
<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

<p><%= link_to "Create New User", new_user_path %></p>

<% @users.each do |x| %>
	<p><%= x.email + ", " %>,
	<%= x.admin %>,
	<%= link_to "Edit", edit_user_path(x.id) %>,
	<%= link_to "View", user_path(x.id) %>,
	<%= link_to "Delete"  %>

<% end %>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

<%= render "form" %>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>