config/routes.rb
Rails.application.routes.draw do

  if Rails.env.development?
    root 'main#amalgam'
  else
    root 'main#home'
  end

  get 'home' => "main#home"

  resources :games do   
    resources :brackets do
      resources :maps do
        resources :gametypes
      end
    end
  end
  resources :brackets, only: :index
  
  resources :tournaments

  resources :examples

  devise_for :users
  devise_scope :user do
    get '/signout', to: 'devise/sessions#destroy', as: :signout
  end

  resources :users

  get 'admin/main' => 'admin_panels#main'
  get 'control' => 'admin_panels#control_panel'

  get 'new-form' => 'examples#new_form'

end

app/models/game.rb
class Game < ActiveRecord::Base
	has_attached_file :image_file, styles: {large: "750x500>", medium: "450x450>", small: "300x250>", tiny: "100x100>" }, default_url: "/images/:style/missing.png"
	validates_attachment_content_type :image_file, content_type: /\Aimage\/.*\z/

	validates_uniqueness_of :title

	has_many :brackets
	has_many :gametypes
	has_many :maps

	scope :fps, -> { where(category: 'fps') }
	scope :moba, -> { where(category: 'moba') }
	scope :more, -> { where(category: 'more') }
	scope :legacy, -> { where(category: 'legacy') }

end

app/models/gametype.rb
class Gametype < ActiveRecord::Base
  belongs_to :game
  belongs_to :map
  belongs_to :bracket
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, except: [:index, :new, :create]
  load_and_authorize_resource

  def index
    @games = Game.all 
  end

  def new
    @game = Game.new
  end

  def create
    @game = Game.new(game_params)
    if @game.save
      redirect_to games_path
    else
      render :new 
    end
  end

  def edit

  end

  def update
     @game.update(game_params)
     redirect_to games_path
  end

  def show
  end

  def destroy
    @game.destroy
    flash[:success] = "Game Destroyed"
    redirect_to games_path
  end

  private

  def set_game 
    @game = Game.find(params[:id])
  end

  def game_params
    params.require(:game).permit(:image, :title, :category, :active, :short_title, :image_file)
  end

end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
	<% if @game.errors.any? %>
		<p><%= pluralize(@game.errors.count, "error") %> errors kept form from submitting succesfully:</p>

		<ul>
			<% @game.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
		</ul>
	<% end %>

	<%= f.label :title %><br>
	<%= f.text_field :title %>
<p></p>
	<%= f.label :short_title %><br>
	<%= f.text_field :short_title %>
<p></p>
	<%= f.label :image_file %><br>
	<%= f.file_field :image_file %>
<p></p>
	<%= f.label :category %><br>
	<%= f.select :category, [['FPS', 'fps'],['MOBA', 'moba'],['More', 'more'],['Legacy', 'legacy']], :class => "select-list" %>
<p></p>
	<%= f.label :active %> <br>
	<%= f.select :active, [['True', true],['False', false]], :class => "select-list" %>
<p></p>
	<%= f.submit %>
<% end %>

app/views/games/create.html.erb
<h1>Games#create</h1>
<p>Find me in app/views/games/create.html.erb</p>

app/views/games/destroy.html.erb
<h1>Games#destroy</h1>
<p>Find me in app/views/games/destroy.html.erb</p>

app/views/games/edit.html.erb
<h1>Games#edit</h1>
<p>Find me in app/views/games/edit.html.erb</p>

<%= render 'form' %>

<%= link_to "Cancel", games_path %> 

app/views/games/index.html.erb
<h1>Games#index</h1>
<p>Find me in app/views/games/index.html.erb</p>

<p><%= link_to "Create New Game", new_game_path %></p>

<% @games.each do |x| %>
<ul>
	<li>
		<%= x.title %>
		<% if x.image_file.url !~ /missing/ %>
			<%= image_tag x.image_file.url(:tiny) %>
		<% end %>
		<%= x.active %>
		<%= x.category.upcase %>
		<span class="index-manage">

		<%= link_to "View", x %>

		<% if can? :update, @article %>
  		<%= link_to "Edit", edit_game_path(x) %>
		<% end %>

		<% if can? :delete, @article %>
  		<%= link_to "Delete", x, method: :delete, data: { confirm: "Are you sure?"} %>
		<% end %>

		<!-- pipe for styling purposes -->
		|

		<%= link_to "Brackets", game_brackets_path(x) %>
		<%= link_to "New Bracket", new_game_bracket_path(x) %>
			
		</span>
	</li>
</ul>
<% end %>


 

app/views/games/new.html.erb
<h1>Games#new</h1>
<p>Find me in app/views/games/new.html.erb</p>

<p><%= link_to "Games Index", games_path %></p>

<%= render 'form' %>

app/views/games/show.html.erb
<h1>Games#show</h1>
<p>Find me in app/views/games/show.html.erb</p>


<p>
	Game Title:
	<%= @game.title %>
</p>

<p>
	Short Title:
	<%= @game.short_title %>
</p>

<p>
	Game ID:
	<%= @game.id %>
</p>

<p>
	Game Image: 
	<%= image_tag @game.image_file.url(:small) %>
</p>

<p>
	Category: 
	<%= @game.category.upcase %>
</p>

<p>
	Active: 
	<%= @game.active %>
</p>

<%= link_to "Index", games_path %>

app/views/games/update.html.erb
<h1>Games#update</h1>
<p>Find me in app/views/games/update.html.erb</p>