config/routes.rb
Rails.application.routes.draw do

  if Rails.env.development?
    root 'main#amalgam'
  else
    root 'main#home'
  end

  get 'home' => "main#home"

  resources :games do   
    resources :brackets do
      resources :maps do
        resources :gametypes
      end
    end
  end
  resources :brackets, only: :index
  
  resources :tournaments

  resources :examples

  devise_for :users
  devise_scope :user do
    get '/signout', to: 'devise/sessions#destroy', as: :signout
  end

  resources :users

  get 'admin/main' => 'admin_panels#main'
  get 'control' => 'admin_panels#control_panel'

  get 'new-form' => 'examples#new_form'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

    def initialize(user)
      user ||= User.new # guest user (not logged in)
        if user.admin?
          can :manage, :all

          can :delete, User do |user|
            !user.admin?
          end
          
        else
          can :read, :all
          # can :manage, Bracket
          # can :manage, :all. if: { }
        end
    end

    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities

end

app/models/bracket.rb
class Bracket < ActiveRecord::Base
	belongs_to :game
	
	has_many :maps
	has_many :gametypes
end

app/models/example.rb
class Example < ActiveRecord::Base
end

app/models/game.rb
class Game < ActiveRecord::Base
	has_attached_file :image_file, styles: {large: "750x500>", medium: "450x450>", small: "300x250>", tiny: "100x100>" }, default_url: "/images/:style/missing.png"
	validates_attachment_content_type :image_file, content_type: /\Aimage\/.*\z/

	validates_uniqueness_of :title

	has_many :brackets
	has_many :gametypes
	has_many :maps

	scope :fps, -> { where(category: 'fps') }
	scope :moba, -> { where(category: 'moba') }
	scope :more, -> { where(category: 'more') }
	scope :legacy, -> { where(category: 'legacy') }

end

app/models/gametype.rb
class Gametype < ActiveRecord::Base
  belongs_to :game
  belongs_to :map
  belongs_to :bracket
end

app/models/map.rb
class Map < ActiveRecord::Base
  belongs_to :game
  belongs_to :bracket
  has_many :gametypes
end

app/models/tournament.rb
class Tournament < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/main_controller.rb
class MainController < ApplicationController
	
	# layout "_hero"

  def home
  end

  def amalgam
  end

  def layout
  end

end

app/controllers/maps_controller.rb
class MapsController < ApplicationController

  before_action :set_game, :set_bracket
  before_action :set_map, except: [:new, :create, :index]

  def index
    @maps = @bracket.maps
  end

  def new
    @map = @bracket.maps.new
  end

  def create
    @map = @bracket.maps.new(map_params)
    if @map.save
      flash[:success] = "Map succesfully saved."
      redirect_to game_bracket_maps_path(@game, @bracket)
    end
  end

  def edit
  end

  def update
  end

  def show

  end

  def destroy
  end

  private 

  def set_map
    if params[:map_id].present?
      @map = Map.find(params[:map_id])
    else
      @map = Map.find(params[:id])
    end
  end

  def map_params 
    params.require(:map).permit(:name)
  end

  def set_game
    if params[:game_id].present?
      @game = Game.find(params[:game_id])
    end    
  end

  def set_bracket
    if params[:bracket_id].present?
      @bracket = Bracket.find(params[:bracket_id])
    end
  end  
end

app/helpers/admin_panels_helper.rb
module AdminPanelsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brackets_helper.rb
module BracketsHelper
end

app/helpers/examples_helper.rb
module ExamplesHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/gametypes_helper.rb
module GametypesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/tournaments_helper.rb
module TournamentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<div class="hello"></div>

app/views/layouts/_hero.html.erb
<div class="full-hero">
	<div class="grid">
		<div class="home-gradient">
			<h3><i class="fa fa-cubes"></i>Mythic Gaming</h3>
		</div>
		<div class="home-carousel">
		</div>
	</div>
</div>

app/views/layouts/_navbar.html.erb
<!-- Beginning of Nav -->
<ul class="w3-navbar w3-large w3-left-align"> <!-- Beginning of W3 Nav -->
<nav class="navvy">
  <li class="w3-hide-medium w3-hide-large w3-black w3-opennav w3-right">
    <a href="javascript:void(0);" onclick="myFunction()">☰</a>
  </li>
  <!-- Logo -->
  <li>
    <%= link_to root_path, :class => "logo-link" do %>
      <i class="fa fa-cubes"></i> Mythic Gaming
    <% end %>  
  </li>

  <!-- Standard Link for Navbar Example -->
  <!-- <li class="w3-hide-small"><a href="#">Link 3</a></li> -->

 <!--  Main Nav -->
  <li class="w3-dropdown-hover w3-hide-medium w3-hide-small">
    <%= link_to "FPS Games", root_path, :class => "fps-link" %>
    <div class="w3-dropdown-content w3-card-4 fps-drop-content">
      <% Game.fps.each do |x| %>
        <%= link_to "#{x.short_title}", x %>
      <% end %>
    </div>
  </li>
  <li class="w3-dropdown-hover w3-hide-medium w3-hide-small">
    <%= link_to "MOBA Games", root_path, :class => "moba-link" %>
    <div class="w3-dropdown-content w3-card-4 moba-drop-content">
      <% Game.moba.each do |x| %>
        <%= link_to "#{x.short_title}", x %>
      <% end %>
    </div>
  </li>
  <li class="w3-dropdown-hover w3-hide-medium w3-hide-small">
    <%= link_to "More Games", root_path, :class => "more-link" %>
    <div class="w3-dropdown-content w3-card-4 more-drop-content">
      <% Game.more.each do |x| %>
        <%= link_to "#{x.short_title}", x %>
      <% end %>
    </div>
  </li>
   <li class="w3-dropdown-hover w3-hide-medium w3-hide-small">
    <%= link_to "Legacy Games", root_path, :class => "legacy-link" %>
    <div class="w3-dropdown-content w3-card-4 legacy-drop-content">
      <% Game.legacy.each do |x| %>
        <%= link_to "#{x.short_title}", x %>
      <% end %>
    </div>
  </li>
  <li class="w3-hide-large w3-hide-small"><a href="javascript:void(0)" onclick="w3_open()">All Games <i class="fa fa-caret-down"></i></a></li>
  <li class="w3-dropdown-hover w3-hide-small">
    <a href="#">Information</a>
    <div class="w3-dropdown-content w3-white w3-card-4">
      <a href="#">Link 1</a>
      <a href="#">Link 2</a>
      <a href="#">Link 3</a>
    </div>
  </li>
  <li class="w3-hide-small"><%= link_to ("<i class='fa fa-life-ring'></i>").html_safe %></li>

  <!-- Admin -->
  <% if current_user && current_user.admin? %>
    <li class="w3-hide-small"><%= link_to "Admin", control_path %></li>
  <% end %>
 <!-- End of main nav -->

  <!-- Right Aligned Links -->
  <% if user_signed_in? %>
    <li class="w3-dropdown-hover w3-hide-small w3-right">
      <a href="#"><i class="fa fa-user"></i> Profile</a>
      <div class="w3-dropdown-content w3-white w3-card-4">
        <%= link_to "Edit Profile", edit_user_registration_path %>
        <a href="#">Settings</a>
        <a href="#">Invites</a>
        <a href="#">Payment</a>
        <hr>
        <%= link_to "Log out", signout_path %>
      </div>
    </li>
  <% else %>
    <li class="w3-right w3-hide-small">
      <%= link_to new_user_session_path, :class => "log-in-link" do %>
       <!--  <i class="fa fa-anchor"></i> --> Log in
      <% end %>
    </li>
    <li class="w3-right w3-hide-small">
      <%= link_to new_user_registration_path, :class => "sign-up-link" do %>
        <!-- <i class="fa fa-check"></i> --> Sign up
      <% end %>
    </li>
  <% end %> <!-- End of Right Aligned Links -->

  
</nav> <!-- End of Nav -->
</ul> <!-- End of W3 Nav -->


<!-- What Shows up In Mobile Menu  -->
<div id="demo" class="w3-hide w3-hide-large w3-hide-medium">
  <ul class="w3-navbar w3-left-align w3-large w3-black">
    <li><a href="javascript:void(0)" onclick="w3_open()">Games</a></li>
    <li><%= link_to "Information", brackets_path %></li>
    <% if user_signed_in? %>
      <li><%= link_to "Profile" %></li>
      <li><%= link_to "Log out", signout_path %></li>
    <% else %>
      <li><%= link_to "Log in", new_user_session_path %></li>
      <li><%= link_to "Sign up", new_user_registration_path %></li>
    <% end %>
  </ul>
</div> <!-- End of Mobile Menu -->

<!-- DropNav Links -->
<nav class="w3-dropnav w3-card-2" style="display:none" id="myDropnav">
  <div class="w3-container">
  <span onclick="w3_close()" class="w3-closebtn w3-xlarge" title="Close Menu">&times;</span>
  </div>
  <div class="w3-row-padding w3-padding-bottom">
    <div class="w3-quarter fps-dropnav dropnav-links">
      <h5>FPS</h5>
      <% Game.fps.each do |x| %>
        <%= link_to "#{x.short_title}", brackets_path %>
      <% end %>
    </div>
    <div class="w3-quarter moba-dropnav dropnav-links">
    <h5>MOBA</h5>
     <% Game.moba.each do |x| %>
        <%= link_to "#{x.short_title}", brackets_path %>
      <% end %>
    </div>
    <div class="w3-quarter more-dropnav dropnav-links">
    <h5>MORE</h5>
     <% Game.more.each do |x| %>
        <%= link_to "#{x.short_title}", brackets_path %>
      <% end %>
    </div>
    <div class="w3-quarter legacy-dropnav dropnav-links">
    <h5>Legacy</h5>
     <% Game.legacy.each do |x| %>
        <%= link_to "#{x.short_title}", brackets_path %>
      <% end %>
    </div>
  </div>
  <br>
</nav> <!-- End of Drop Nav -->


<script>
var x = document.getElementById("myDropnav");
function w3_open() {
    if (x.className.indexOf("w3-show") == -1) {
        x.className += " w3-show";
    } else {
        x.className = x.className.replace(" w3-show", "");
    }
}
function w3_close() {
    x.className = x.className.replace(" w3-show", "");
}
function myFunction() {
    var x = document.getElementById("demo");
    if (x.className.indexOf("w3-show") == -1) {
        x.className += " w3-show";
    } else {
        x.className = x.className.replace(" w3-show", "");
    }
}
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>MythicGamingApp</title>
  <%= stylesheet_link_tag 'application', params[:controller], media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', params[:controller], 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body>

  <div class="whole-doc">
    <%= render 'layouts/navbar' %>
      <div class="main-content">
        <%= yield %>
      </div>
    <%= render 'layouts/footer' %>
  </div>

</body>
</html>